[package]
name = "heirloom-ika"
version = "0.1.0"
description = "Heirloom IKA - Multi-chain digital estate on Solana with Ika dWallet"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "heirloom_ika"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = "1.0.2"
anchor-spl = "1.0.2"
ika-dwallet-anchor = { git = "https://github.com/dwallet-labs/ika-pre-alpha" }
solana-instructions-sysvar = "3.0.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
