words = [
    "Apalis",
    "Ethereum",
    "Lamport",
    "Lulo",
    "USDC",
    "bunx",
    "codama",
    "dwallet",
    "historiah",
    "ika",
    "kamino",
    "onchain",
    "pda",
    "sysvar",
]
