export * from "./generated";

export * from "./constants"

/* FIXME: GET RID OF ME ONCE PDA IS AUTOGENERATED */
import {
  getAddressEncoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export type AssetRecordSeeds = {
  estate: Address;
  mint: Address;
};

export async function findAssetRecordPda(
  seeds: AssetRecordSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "heirRS7LknVZiPvnZqEpfcAzFDvXgv96wMH7ByGHukg" as Address<"heird3FWfGcobFHyZEC6FMaPBPN3oWqsh8ZqVQXz5Kz">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(new Uint8Array([97, 115, 115, 101, 116])),
      getAddressEncoder().encode(seeds.estate),
      getAddressEncoder().encode(seeds.mint),
    ],
  });
}
